version: '3.8'

services:
  db:
    image: mariadb:10.5
    container_name: glpi_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  glpi:
    image: diouxx/glpi
    container_name: glpi_web
    restart: always
    ports:
      - "80:80"
    environment:
      TIMEZONE: ${TIMEZONE}
    volumes:
      - glpi_data:/var/www/html
    depends_on:
      - db

volumes:
  db_data:
  glpi_data:
